services:
  - type: web
    name: fraud-analytics-dashboard
    env: python
    plan: free # <-- THIS LINE IS CRITICAL
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    python:
      version: 3.10.12 # <-- This is the correct way to specify the version
